### ISSUE TITLE
Error in sys.excepthook upon defining the vault folder path.

### ISSUE THREAD

**Issue by szfkamil** [natelandau/obsidian-metadata#20]
I defined the folder path, and re-running the program left me in the same place with the same lines and errors as before.

[See here:](https://imgur.com/a/q3lbDum)

**Comment by natelandau** [comment]
Sorry you're having issues and thank you for reporting them. There seems to be an issue indexing your frontmatter YAML.  Would you mind pasting a sample of your frontmatter below?

**Comment by szfkamil** [comment]
Hey! Here's the default note template which is applied on around 1 in 4 notes in my vault.
```
---
creation_date: <% tp.date.now("yyyy-MM-DDTHH:mm") %> 
publish: false
cssclass:
type:

Parent:
Sibling:
Child:
Friend: 
---
```

**Comment by natelandau** [comment]
unfortunately, I can't recreate the issue. The most likely culprit is an error in the frontmatter of one of your notes.

version `0.6.1` contains better error handling that should help you find the error. run `pip install obsidian-metadata --upgrade` to update to this version and then try running it again.

I'd recommend using an online [yaml validator](https://www.yamllint.com/) to see if you can identify the problem.

I am happy to continue to find an issue but to do so I'll need the following from you:

1. The complete traceback (not a video)
2. a few examples of actual metadata from your notes, not just the template.

Hope this all helps

**Comment by szfkamil** [comment]
The new version showed me the error; I expected the program to stay intact if one note among thousands had an invalid YAML. It's good that the new version contains better error handling!

<img width="499" alt="Screenshot 2023-03-08 at 22 33 09" src="https://user-images.githubusercontent.com/82778513/223855235-d4074809-5228-4827-89a7-244b5b8d30c4.png">

**Comment by Andyspickle** [comment]
Every time I run `obsidian-metadata` from the terminal, I am seeing this error, not sure how to fix it. Any help would be appreciated,

```bash
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/typer/main.py", line 72, in except_hook
    rich_tb = Traceback.from_exception(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/rich/traceback.py", line 335, in from_exception
    rich_traceback = cls.extract(
                     ^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/rich/traceback.py", line 449, in extract
    locals={
           ^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/rich/traceback.py", line 450, in <dictcomp>
    key: pretty.traverse(
         ^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/rich/pretty.py", line 852, in traverse
    node = _traverse(_object, root=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/rich/pretty.py", line 647, in _traverse
    args = list(iter_rich_args(rich_repr_result))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/rich/pretty.py", line 614, in iter_rich_args
    for arg in rich_args:
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/models/vault.py", line 86, in __rich_repr__
    yield "num_notes_in_scope", len(self.notes_in_scope)
                                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Vault' object has no attribute 'notes_in_scope'

Original exception was:
Traceback (most recent call last):
  File "/Users/drew/.asdf/installs/python/3.11.2/bin/obsidian-metadata", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/typer/core.py", line 716, in main
    return _main(
           ^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/cli.py", line 157, in main
    application.application_main()
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/models/application.py", line 48, in application_main
    self._load_vault()
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/models/application.py", line 37, in _load_vault
    self.vault: Vault = Vault(config=self.config, dry_run=self.dry_run)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/models/vault.py", line 70, in __init__
    self.all_notes: list[Note] = [
                                 ^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/models/vault.py", line 71, in <listcomp>
    Note(note_path=p, dry_run=self.dry_run) for p in self.all_note_paths
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/models/notes.py", line 64, in __init__
    self.inline_metadata: InlineMetadata = InlineMetadata(self.file_content)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/models/metadata.py", line 380, in __init__
    self.dict: dict[str, list[str]] = self._grab_inline_metadata(file_content)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/drew/.asdf/installs/python/3.11.2/lib/python3.11/site-packages/obsidian_metadata/models/metadata.py", line 407, in _grab_inline_metadata
    for k, v in stripped_null_values:
        ^^^^
ValueError: not enough values to unpack (expected 2, got 1)
```
