### ISSUE TITLE
Error on first run

### ISSUE THREAD

**Issue by fishcasa** [natelandau/obsidian-metadata#30]
When I first run obsidian-metadata, I get the ASCII logo screen and it asks me for path to vault. When I put the path in and hit enter, it seems to hang. If I hit enter agian, it errors out like this

```
`? Enter a path to Obsidian vault: WorkBrain\
INFO     | Created default configuration file at 'C:\Users\henry\.obsidian_metadata.toml'
ERROR    | Could not parse 'C:\Users\henry\.obsidian_metadata.toml'
C:\Users\henry\Desktop\Notes>`
```

.obsidian_metadata.toml is created and looks like the example:
```
# Add another vault by replicating this section and changing the name
["Vault 1"] # Name of the vault.

    # Path to your obsidian vault
    path = "C:\Users\henry\Desktop\Notes\WorkBrain"

    # Folders within the vault to ignore when indexing metadata
    exclude_paths = [".git", ".obsidian"]

    # Location to add new metadata. One of:
    #    TOP:            Directly after frontmatter.
    #    AFTER_TITLE:    After the first header following frontmatter.
    #    BOTTOM:         The bottom of the note
    insert_location = "BOTTOM"

```
I am on Windows 11 Pro, Python 3.11.2, Obsidian 1.2.0

**Comment by fishcasa** [comment]
It ran then failed with this output.

```

   ___  _         _     _ _
  / _ \| |__  ___(_) __| (_) __ _ _ __
 | | | | '_ \/ __| |/ _` | |/ _` | '_ \
 | |_| | |_) \__ \ | (_| | | (_| | | | |
  \___/|_.__/|___/_|\__,_|_|\__,_|_| |_|
 |  \/  | ___| |_ __ _  __| | __ _| |_ __ _
 | |\/| |/ _ \ __/ _` |/ _` |/ _` | __/ _` |
 | |  | |  __/ || (_| | (_| | (_| | || (_| |
 |_|  |_|\___|\__\__,_|\__,_|\__,_|\__\__,_|

Error in sys.excepthook:
Traceback (most recent call last):
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\typer\main.py", line 72, in except_hook    rich_tb = Traceback.from_exception(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\traceback.py", line 335, in from_exception
    rich_traceback = cls.extract(
                     ^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\traceback.py", line 449, in extract
    locals={
           ^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\traceback.py", line 450, in <dictcomp>
    key: pretty.traverse(
         ^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\pretty.py", line 852, in traverse
    node = _traverse(_object, root=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\pretty.py", line 647, in _traverse    args = list(iter_rich_args(rich_repr_result))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\rich\pretty.py", line 614, in iter_rich_args
    for arg in rich_args:
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\obsidian_metadata\models\vault.py", line 86, in __rich_repr__
    yield "num_notes_in_scope", len(self.notes_in_scope)
                                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Vault' object has no attribute 'notes_in_scope'

Original exception was:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Scripts\obsidian-metadata.exe\__main__.py", line 7, in <module>
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\typer\main.py", line 328, in __call__
    raise e
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\typer\main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\typer\core.py", line 716, in main
    return _main(
           ^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\typer\core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\typer\main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\obsidian_metadata\cli.py", line 168, in main
    application.application_main()
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\obsidian_metadata\models\application.py", line 48, in application_main
    self._load_vault()
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\obsidian_metadata\models\application.py", line 37, in _load_vault
    self.vault: Vault = Vault(config=self.config, dry_run=self.dry_run)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\obsidian_metadata\models\vault.py", line 70, in __init__
    self.all_notes: list[Note] = [
                                 ^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\obsidian_metadata\models\vault.py", line 71, in <listcomp>
    Note(note_path=p, dry_run=self.dry_run) for p in self.all_note_paths
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\site-packages\obsidian_metadata\models\notes.py", line 57, in __init__
    self.file_content: str = self.note_path.read_text()
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\pathlib.py", line 1059, in read_text
    return f.read()
           ^^^^^^^^
  File "C:\Users\henry\AppData\Local\Programs\Python\Python311\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 188: character maps to <undefined>
PS C:\Users\henry>
```

**Comment by fishcasa** [comment]
I was able to get it going in the Windows Subsystem for Linux, same machine, same vault, using linux path '/mnt/c/Users/henry/Desktop/Notes/WorkBrain"

```

   ___  _         _     _ _
  / _ \| |__  ___(_) __| (_) __ _ _ __
 | | | | '_ \/ __| |/ _` | |/ _` | '_ \
 | |_| | |_) \__ \ | (_| | | (_| | | | |
  \___/|_.__/|___/_|\__,_|_|\__,_|_| |_|
 |  \/  | ___| |_ __ _  __| | __ _| |_ __ _
 | |\/| |/ _ \ __/ _` |/ _` |/ _` | __/ _` |
 | |  | |  __/ || (_| | (_| | (_| | || (_| |
 |_|  |_|\___|\__\__,_|\__,_|\__,_|\__\__,_|

SUCCESS  | Loaded 3157 notes from 3157 total notes
┌───────────────────────────┬────────────────────────────────────────────┐
│ Vault                     │ /mnt/c/Users/henry/Desktop/Notes/WorkBrain │
│ Backup                    │ None                                       │
│ Notes in scope            │ 3157                                       │
│ Notes excluded from scope │ 0                                          │
│ Active filters            │ 0                                          │
│ Notes with changes        │ 0                                          │
│ Insert Location           │ Bottom                                     │
└───────────────────────────┴────────────────────────────────────────────┘
INPUT    | What do you want to do? (Use arrow keys)
   -------------------------------
 » Vault Actions
   Export Metadata
   Inspect Metadata
   Filter Notes in Scope
   -------------------------------
   Import bulk changes from CSV
   Add Metadata
   Delete Metadata
   Rename Metadata
   Reorganize Metadata
   -------------------------------
   Review Changes
   Commit Changes
   -------------------------------
   Quit
```

**Comment by muteboy** [comment]
> thanks for reporting this. There appears to be an issue with the way TOML deals with strings where you will need to double escape the backslashes in your path. i.e.
> 
> from this:
> 
> ```shell
> # Path to your obsidian vault
>     path = "C:\Users\henry\Desktop\Notes\WorkBrain"
> ```
> 
> to this:
> 
> ```toml
> # Path to your obsidian vault
>     path = "C:\\Users\\henry\\Desktop\\Notes\\WorkBrain"
> ```
> 
> I'll be releasing some improvements to the documentation to make this more clear soon. Thanks for helping me identify this issue, I don't have access to a Windows machine so I had no idea that this was an issue.
> 
> let me know if the changes outlined above fix the problem

I had the same problem, and used the double backslash, and it worked. Thank you
