### ISSUE TITLE
Vault correct but getting error

### ISSUE THREAD

**Issue by dxcore35** [natelandau/obsidian-metadata#70]
I have double check the validity of my vault. But still im getting this error

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/typer/main.py", line 72, in except_hook
    rich_tb = Traceback.from_exception(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rich/traceback.py", line 335, in from_exception
    rich_traceback = cls.extract(
                     ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rich/traceback.py", line 449, in extract
    locals={
           ^
  File "/opt/homebrew/lib/python3.11/site-packages/rich/traceback.py", line 450, in <dictcomp>
    key: pretty.traverse(
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rich/pretty.py", line 853, in traverse
    node = _traverse(_object, root=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rich/pretty.py", line 648, in _traverse
    args = list(iter_rich_args(rich_repr_result))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/rich/pretty.py", line 615, in iter_rich_args
    for arg in rich_args:
  File "/opt/homebrew/lib/python3.11/site-packages/obsidian_metadata/models/vault.py", line 89, in __rich_repr__
    yield "num_notes_in_scope", len(self.notes_in_scope)
                                    ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Vault' object has no attribute 'notes_in_scope'

Original exception was:
Traceback (most recent call last):
  File "/opt/homebrew/bin/obsidian-metadata", line 8, in <module>
    sys.exit(app())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/typer/core.py", line 716, in main
    return _main(
           ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/obsidian_metadata/cli.py", line 168, in main
    application.application_main()
  File "/opt/homebrew/lib/python3.11/site-packages/obsidian_metadata/models/application.py", line 48, in application_main
    self._load_vault()
  File "/opt/homebrew/lib/python3.11/site-packages/obsidian_metadata/models/application.py", line 37, in _load_vault
    self.vault: Vault = Vault(config=self.config, dry_run=self.dry_run)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/obsidian_metadata/models/vault.py", line 73, in __init__
    self.all_notes: list[Note] = [
                                 ^
  File "/opt/homebrew/lib/python3.11/site-packages/obsidian_metadata/models/vault.py", line 74, in <listcomp>
    Note(note_path=p, dry_run=self.dry_run) for p in self.all_note_paths
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/obsidian_metadata/models/notes.py", line 72, in __init__
    self.metadata = self._grab_all_metadata(self.file_content)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/obsidian_metadata/models/notes.py", line 104, in _grab_all_metadata
    for key, value in frontmatter.items():
                      ^^^^^^^^^^^^^^^^^

```

**Comment by alberttra** [comment]
i have same problem

**Comment by szfkamil** [comment]
My exact error is:

```
Error in sys.excepthook:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 72, in except_hook
    rich_tb = Traceback.from_exception(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich/traceback.py", line 335, in from_exception
    rich_traceback = cls.extract(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich/traceback.py", line 448, in extract
    locals={
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich/traceback.py", line 449, in <dictcomp>
    key: pretty.traverse(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich/pretty.py", line 887, in traverse
    node = _traverse(_object, root=True)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich/pretty.py", line 683, in _traverse
    args = list(iter_rich_args(rich_repr_result))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/rich/pretty.py", line 650, in iter_rich_args
    for arg in rich_args:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/models/vault.py", line 82, in __rich_repr__
    yield "num_notes", len(self.all_notes)
AttributeError: 'Vault' object has no attribute 'all_notes'

Original exception was:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/obsidian-metadata", line 8, in <module>
    sys.exit(app())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 328, in __call__
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/core.py", line 716, in main
    return _main(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/typer/main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/cli.py", line 204, in main
    application.application_main()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/models/application.py", line 47, in application_main
    self._load_vault()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/models/application.py", line 36, in _load_vault
    self.vault: Vault = Vault(config=self.config, dry_run=self.dry_run)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/models/vault.py", line 70, in __init__
    self.all_notes: list[Note] = [
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/models/vault.py", line 71, in <listcomp>
    Note(note_path=p, dry_run=self.dry_run) for p in self.all_note_paths
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/models/notes.py", line 57, in __init__
    self.frontmatter: Frontmatter = Frontmatter(self.file_content)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/models/metadata.py", line 214, in __init__
    self.dict: dict[str, list[str]] = self._grab_note_frontmatter(file_content)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/obsidian_metadata/models/metadata.py", line 248, in _grab_note_frontmatter
    for k in frontmatter:
TypeError: 'NoneType' object is not iterable
```
